export const ActionTypes = {
    SET_MOVIES : "SET_MOVIES",
    SELECTED_MOVIE: "SELECTED_MOVIE",
    REMOVE_SELECTED_MOVIE: "REMOVE_SELECTED_MOVIE",
    REMOVE_ALL_MOVIE: "REMOVE_ALL_MOVIE",
    SELECTED_KEYWORD: "SELECTED_KEYWORD",
    REMOVE_SELECTED_KEYWORD: "REMOVE_SELECTED_KEYWORD",
    SELECTED_PAGE: "SELECTED_PAGE",
    REMOVE_SELECTED_PAGE: "REMOVE_SELECTED_PAGE"
}